steps:
  - name: "node:10.16.3"
    entrypoint: npm
    args: ["install"]

  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=gcloud-env.yaml.enc
      - --plaintext-file=gcloud-env.yaml
      - --location=global
      - --keyring=${_BUILD_RING}
      - --key=${_KEY}

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - appointment-notification
      - --source=.
      - "--trigger-event=providers/cloud.firestore/eventTypes/document.update"
      - "--trigger-resource=projects/$PROJECT_ID/databases/(default)/documents/appointments/{appointmentId}"
      - --runtime=nodejs10
      - --region=${_REGION}
      - --env-vars-file=gcloud-env.yaml
      - --entry-point=appointmentNotification
